FROM nginx
COPY index.html /usr/share/nginx/html

#docker build -t 449325664824.dkr.ecr.eu-west-2.amazonaws.com/dev:1.0.0 . 

#aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 4493-2566-4824.dkr.ecr.eu-west-2.amazonaws.com
